### ISSUE TITLE
Request: verify bridged token source on bscscan

### ISSUE THREAD

**Issue by Lucas-L** [icon-project/icon-bridge#394]
Hello,  I'd like to know if it's technically possible to verify the source of the assets bridged towards the Binance Smart Chain.

For example: https://bscscan.com/token/0x33acdf0fe57c531095f6bf5a992bf5aa81c94acf#readContract

This step is necessary to gain users trust in the bridged assets. On the same topic, I noticed that the name of the assets is for example: `btp-0x1.icon-sICX`. Will the assets bridged from icon-bridge and BTP share the same contract?

Thanks and congratulations on this release!

**Comment by CyrusVorwald-ICON** [comment]
Hi @Lucas-L, we cannot say for certain whether or not icon-bridge and BTP will share the same contract because BTP is still under development. It's possible that BTP will require a new contract, but we will try to avoid that unless necessary.

We will look into verifying source assets. Thank you for bringing this to our attention.
