### ISSUE TITLE
chore (e2e): run e2e test on PR #445

### ISSUE THREAD

**Issue by bbist** [icon-project/icon-bridge#517]
## Overview

Manually run e2e test and ensure that basic transfer flow is not blocked and relay is not stuck.

## Story

There has been a lot of changes in PR https://github.com/icon-project/icon-bridge/pull/445. We're not sure whether it doesn't break anything. As full e2e is made part of github actions, we'll have to run e2e manually.

## Acceptance Criteria

- Basic set of full flow transfer is working
- Relay is not stuck while running tests

**Comment by manishbista28** [comment]
While running relay, we encountered an error that was triggered by the removal or icon/register_relay.go
After manually placing the register_relay.go, we observed that the function signature of NewReceiver for bsc and icon chains were different.

To merge the branch to main, icon and bsc should have the same NewReceiver signature. So it appears that the PR can not be merged as it is right now. Since relay is not operational until changes are aligned, e2e tests can not be run either.

Other than the ones mentioned above, @bbist , please add any reviews you may have either here or directly to the PR

**Comment by manishbista28** [comment]
some changes were made on the PR to correct existing issues
afterwards, e2e tests were run
inter-chain transfer is working

**Comment by bbist** [comment]
@manishbista28,
Can we check if the BMR is still running? And do a final e2e test run, to ensure everything is working even after a couple of days of BMR continuously running.
